version: '3.8'  # Bạn có thể sử dụng phiên bản cao hơn nếu muốn
services:
  zookeeper:
    image: zookeeper:3.7.0  # Sử dụng hình ảnh chính thức từ Docker Hub
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:latest  # Hình ảnh Bitnami Kafka, cũng ổn định và phổ biến
    ports:
      - "9092:9092"
      - "9094:9094"  # Để có thể kết nối từ localhost
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  # Thêm dòng này
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    depends_on:
      - zookeeper
    volumes:
      - /tmp/kafka-logs:/kafka-logs  # Gắn kết volume cho Kafka logs